import { title } from 'process'
import React from 'react'

export const metadata = {
  title: 'About Bishal Lama',
  description: 'Generated by me',
}
const About = () => {
  return (
    <h1>About me</h1>
  )
}

export default About