import React from 'react'
import Header from './components/Header'
import Footer from './components/Footer'
import ErrorWrapper from './error-wrapper'

export const metadata = {
  title: {
    default: 'Next.js',
    template: '%s | Next.js',
    absolute: 'Welcome to Next.js!',
  },
  description: 'Generated by create next app',
}
const Marketinglayout = ({children}) => {
  return (
    <>
    <html>
      <body>
      <Header />
      <ErrorWrapper>
        {children}
        </ErrorWrapper>
          <Footer />
      </body>
    </html>
    </>
  )
}

export default Marketinglayout
