import React from 'react'
import Header from '../components/Header'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by create next app',
}

const AuthLayout = ({children}) => {
  return (
    <>
    <html>
      <body>
        {children}
          <Footer />
      </body>
    </html>
    </>
  )
}

export default AuthLayout
